### ISSUE TITLE
Can't access the model from HF

### ISSUE THREAD

**Issue by Ron-Caster** [rupeshs/sd3-low-vram#2]
Starting SD3 medium low VRAM...
Python command check :OK
Python version: 3.12.4
C:\SD\sd3-low-vram\env\Lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
Couldn't connect to the Hub: 401 Client Error. (Request ID: Root=1-6684053f-0505f73e1792f4b330e2a489;4b6d25ff-948d-43cb-bc00-b023046e5e18)

Cannot access gated repo for url https://huggingface.co/api/models/stabilityai/stable-diffusion-3-medium-diffusers.
Access to model stabilityai/stable-diffusion-3-medium-diffusers is restricted. You must be authenticated to access it..
Will try to load from local cache.
Traceback (most recent call last):
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/stabilityai/stable-diffusion-3-medium-diffusers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1300, in download
    info = model_info(pretrained_model_name, token=token, revision=revision)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\huggingface_hub\hf_api.py", line 2301, in model_info
    hf_raise_for_status(r)
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\huggingface_hub\utils\_errors.py", line 321, in hf_raise_for_status
    raise GatedRepoError(message, response) from e
huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-6684053f-0505f73e1792f4b330e2a489;4b6d25ff-948d-43cb-bc00-b023046e5e18)

Cannot access gated repo for url https://huggingface.co/api/models/stabilityai/stable-diffusion-3-medium-diffusers.
Access to model stabilityai/stable-diffusion-3-medium-diffusers is restricted. You must be authenticated to access it.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\SD\sd3-low-vram\\app.py", line 11, in <module>
    pipe = StableDiffusion3Pipeline.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 702, in from_pretrained
    cached_folder = cls.download(
                    ^^^^^^^^^^^^^
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\SD\sd3-low-vram\env\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1548, in download
    raise EnvironmentError(
OSError: Cannot load model stabilityai/stable-diffusion-3-medium-diffusers: model is not cached locally and an error occurred while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.

**Comment by KitKyu** [comment]
I had the same issue. The original model is gated so you can use another diffusers repo from huggingface. In app.py I changed the repo to "v2ray/stable-diffusion-3-medium-diffusers", which fixed the issue.
